# Generated by Django 4.1.7 on 2023-03-25 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmntylisting',
            options={'verbose_name_plural': '6. Listings'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name_plural': '7. Listing Attributes'},
        ),
        migrations.AddField(
            model_name='cmntylisting',
            name='swaptuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.swaptuser'),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='swaptuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.swaptuser'),
        ),
    ]
