# Generated by Django 4.1.7 on 2023-03-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cmntylisting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='listings',
            field=models.ManyToManyField(blank=True, to='main.cmntylisting'),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='state',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='street',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='swaptlistingmodel',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
